# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hamish Dickson - technical blog
email: hamish.dickson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog concentrating on functional programming, maths and physics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "hamishdickson.github.com"
twitter_username: _mishy
github_username:  hamishdickson

# Build settings
markdown: kramdown

exclude:
  - src/
  - target/